---
- hosts: swarm
  become: true
  become_method: sudo
  become_user: root

  vars:
    ghcr_user: "{{ lookup('env','GHCR_USER') }}"
    ghcr_token: "{{ lookup('env','GHCR_TOKEN') }}"

  tasks:
    - name: Add host to known_hosts
      ansible.builtin.known_hosts:
        path: /home/ubuntu/.ssh/known_hosts
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
        state: present

    - name: Ensure .ssh directory exists
      become: true
      become_user: ubuntu
      file:
        path: /home/ubuntu/.ssh
        state: directory
        mode: '0700'

    - name: Copy private SSH key
      become: true
      become_user: ubuntu
      copy:
        dest: /home/ubuntu/.ssh/id_rsa
        content: "{{ lookup('env', 'REPO_SSH_KEY') }}"
        mode: '0600'
      no_log: true

    - name: Add GitHub.com to known_hosts for ubuntu
      become: true
      become_user: ubuntu
      ansible.builtin.known_hosts:
        path: /home/ubuntu/.ssh/known_hosts
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -H github.com') }}"

    - name: Install Git if missing
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure /opt/todo-app exists and is owned by ubuntu
      ansible.builtin.file:
        path: /opt/todo-app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clone or update private todo-app repo via SSH
      become: true
      become_user: ubuntu
      ansible.builtin.git:
        repo: git@github.com:anusmemon226/ci-cd_assignment.git
        dest: /opt/todo-app
        version: main
        key_file: /home/ubuntu/.ssh/id_rsa
        accept_hostkey: yes

    - name: Wait for cloud-init to finish
      wait_for:
        path: /var/lib/cloud/instance/boot-finished
        state: present
        timeout: 120

    - name: Update apt cache (with retries)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker-ce
        update_cache: yes

    - name: Ensure Docker is running
      service:
