---
- hosts: swarm
  become: true
  become_method: sudo
  become_user: root

  vars:
      ghcr_user: "{{ lookup('env','GHCR_USER') }}"
      ghcr_token: "{{ lookup('env','GHCR_TOKEN') }}"

  tasks:
      - name: Ensure .ssh directory for ubuntu
        file:
            path: /home/ubuntu/.ssh
            state: directory
            mode: "0700"
            owner: ubuntu
            group: ubuntu

      - name: Install Git if missing
        ansible.builtin.apt:
            name: git
            state: present
            update_cache: yes

      
